In [29]:
# Import packages
import numpy as np
import pandas as pd

# Load data
df = pd.read_parquet('data_exjobb_070425.parquet')
df.head()

,TransactionId,SalePrice,Lat,Lon,BuildingAge,UtilityArea,LotArea,QualityScore,CloseToBeach,EnergyPerformance,...,MunicipalityMoveInFromCountyFrac,MunicipalityMoveOutToCountyFrac,MunicipalityMoveInFrac2yrChangeMean,MunicipalityMoveOutFrac2yrChangeMean,MunicipalityMoveInFromCountyFrac2yrChangeMean,MunicipalityMoveOutToCountyFrac2yrChangeMean,MunicipalityPopulationMeanDeviation,MedianRentMunicipality,MedianRentMunicipality2yrFracChangeMean,MedianRentMunicipalityMeanDeviation
0,10006194,3200000,56.742153,16.291778,48,143,480,36,0,60.0,...,0.025551,0.021314,0.001816,0.004082,0.000930,0.003437,4.373830,1155.0,0.091030,1.123790
1,10006232,1700000,57.278909,13.646019,54,120,750,32,0,114.0,...,0.010123,0.013869,-0.007777,0.006713,-0.001110,0.002518,1.843030,999.0,0.013451,0.972005
2,10006302,3500000,58.328009,15.103299,47,169,592,30,0,NaN,...,0.034871,0.028112,-0.003267,0.003278,-0.000932,0.000765,1.738860,1046.0,0.075010,1.017735
3,10006371,11200000,57.739437,14.122176,128,250,3311,30,0,88.0,...,0.013410,0.012764,-0.001062,0.001830,0.000457,0.000039,8.857676,1059.0,0.061507,1.030384
4,10006399,591000,57.784585,16.146614,112,87,3406,28,0,101.0,...,0.006766,0.006466,-0.001024,-0.000181,0.000441,0.000045,2.279611,909.0,0.009151,0.884437

In [30]:
dataframe = df.copy()
Targets = pd.DataFrame(dataframe['LogAdjSalePrice202006'])
# print(dataframe[f'{dataframe.axes[1][0]}'])
to_drop = ['TransactionId', 'BaseAreaName', 'DesoArea', 'geometry', 'DistAnyCity', 'DistAnyWater', 'SalePrice', 'LogAdjSalePrice202006', 'LogSalePrice',
            'AdjSalePrice202006']

dataframe = dataframe.drop(to_drop, axis=1)
dataframe.head()

,Lat,Lon,BuildingAge,UtilityArea,LotArea,QualityScore,CloseToBeach,EnergyPerformance,EnergyClass,HasWater,...,MunicipalityMoveInFromCountyFrac,MunicipalityMoveOutToCountyFrac,MunicipalityMoveInFrac2yrChangeMean,MunicipalityMoveOutFrac2yrChangeMean,MunicipalityMoveInFromCountyFrac2yrChangeMean,MunicipalityMoveOutToCountyFrac2yrChangeMean,MunicipalityPopulationMeanDeviation,MedianRentMunicipality,MedianRentMunicipality2yrFracChangeMean,MedianRentMunicipalityMeanDeviation
0,56.742153,16.291778,48,143,480,36,0,60.0,D,1,...,0.025551,0.021314,0.001816,0.004082,0.000930,0.003437,4.373830,1155.0,0.091030,1.123790
1,57.278909,13.646019,54,120,750,32,0,114.0,D,1,...,0.010123,0.013869,-0.007777,0.006713,-0.001110,0.002518,1.843030,999.0,0.013451,0.972005
2,58.328009,15.103299,47,169,592,30,0,NaN,None,1,...,0.034871,0.028112,-0.003267,0.003278,-0.000932,0.000765,1.738860,1046.0,0.075010,1.017735
3,57.739437,14.122176,128,250,3311,30,0,88.0,C,1,...,0.013410,0.012764,-0.001062,0.001830,0.000457,0.000039,8.857676,1059.0,0.061507,1.030384
4,57.784585,16.146614,112,87,3406,28,0,101.0,F,1,...,0.006766,0.006466,-0.001024,-0.000181,0.000441,0.000045,2.279611,909.0,0.009151,0.884437

In [31]:
Targets.head()
Targets.to_parquet('ready_targets.parquet')

In [32]:
def change_data(dataframe_original):
    """Takes a dataframe and finds the columns with values that are non-numerical and assigns each unique non-numerical value a numerical value."""
    dataframe = dataframe_original.copy()
    # rows = np.shape(dataframe)[0]
    cols = np.shape(dataframe)[1]
    print(type(dataframe))
    # print(cols, rows)

    for col in range(cols):
        c = type(dataframe.iloc[0, col]) # Value of the first element in column i row 1
        # print(c)
        if c != np.float64 and c != np.int64:
            a = dataframe.iloc[:, col].unique()   # Gives the unique values of a given column
            number_of_unique_values = np.shape(a)[0]
            b = np.linspace(1, number_of_unique_values, number_of_unique_values) / number_of_unique_values
            # a.reshape(len(a),1)
            # print(np.shape(a), a, "a[0]", a[0], type(a[0]))
            """
            b = np.zeros(number_of_unique_values)
            for j in range(number_of_unique_values):
                b[j] = j / number_of_unique_values
            """
            changed_data = pd.DataFrame(dataframe[f'{dataframe.axes[1][col]}'].copy())
            # print("changed_data", changed_data, " dataframe", dataframe[f'{dataframe.axes[1][col]}'])
            # print("changed data", type(changed_data))
            for j in range(number_of_unique_values):
                # print("col",col)
                # print(dataframe[f'{dataframe.axes[1][col]}'])
                # changed_data = dataframe[f'{dataframe.axes[1][col]}'].copy()
                
                # print(j, "type", type(a[j]), type(b[j]))
                # print("value", a[j], b[j])
                if a[j] == None:
                    changed_data = changed_data.replace('None', b[j])
                else:
                    changed_data = changed_data.replace(a[j], b[j], regex=False)
                    
                    
            print("changed data", changed_data)
            dataframe[f'{dataframe.axes[1][col]}'] = changed_data
            print("dataframe", dataframe[f'{dataframe.axes[1][col]}'])
            """
            for row in range(rows):
                for j in range(number_of_unique_values):
                    if dataframe.iloc[row, col] == a[j]:
                        dataframe.iloc[row, col] = b[j]"""
            

    return dataframe.fillna(0) # Returns the changed data with NaN values changed to zero.

In [33]:
dataframe = dataframe.iloc[0:100, 1:20].copy()
# print(dataframe.iloc[1, 10])
# print(dataframe[5, f'{dataframe.axes[1][15]}'])
changed_data = change_data(dataframe)
print(changed_data, np.shape(changed_data))

<class 'pandas.core.frame.DataFrame'>
changed data     EnergyClass
0      0.142857
1      0.142857
2           NaN
3      0.428571
4      0.571429
..          ...
95          NaN
96     0.142857
97     0.142857
98     0.857143
99     0.857143

[100 rows x 1 columns]
dataframe 0     0.142857
1     0.142857
2          NaN
3     0.428571
4     0.571429
        ...
95         NaN
96    0.142857
97    0.142857
98    0.857143
99    0.857143
Name: EnergyClass, Length: 100, dtype: float64
changed data    EstimatedContractDate
0               0.016129
1    2021-05-04 00:00:00
2    2021-04-21 00:00:00
3    2021-06-10 00:00:00
4    2021-07-05 00:00:00
..                   ...
95   2021-07-28 00:00:00
96   2021-06-23 00:00:00
97   2021-06-03 00:00:00
98   2021-07-04 00:00:00
99   2021-06-10 00:00:00

[100 rows x 1 columns]
dataframe 0                0.016129
1     2021-05-04 00:00:00
2     2021-04-21 00:00:00
3     2021-06-10 00:00:00
4     2021-07-05 00:00:00
             ...
95    2021-07-28 00:00:00
96    2021-06-23 00:00:00
97    2021-06-03 00:00:00
98    2021-07-04 00:00:00
99    2021-06-10 00:00:00
Name: EstimatedContractDate, Length: 100, dtype: object
          Lon  BuildingAge  UtilityArea  LotArea  QualityScore  CloseToBeach  \
0   16.291778           48          143      480            36             0
1   13.646019           54          120      750            32             0
2   15.103299           47          169      592            30             0
3   14.122176          128          250     3311            30             0
4   16.146614          112           87     3406            28             0
..        ...          ...          ...      ...           ...           ...
95  14.609514          121           38      693            25             0
96  15.594482           55          145      804            33             0
97  15.856211           46          139      355            23             0
98  16.462127           43          154      957            38             0
99  16.158767           75          119     1027            43             0

    EnergyPerformance  EnergyClass  HasWater  HasSewer  TaxRegionIdTp10  \
0                60.0     0.142857         1         1           880008
1               114.0     0.142857         1         1           662006
2                 0.0     0.000000         1         1           586013
3                88.0     0.428571         1         0           680305
4               101.0     0.571429         1         1           883900
..                ...          ...       ...       ...              ...
95                0.0     0.000000         0         1          1083004
96               58.0     0.142857         1         1          1080028
97               97.0     0.142857         1         1           884006
98              123.0     0.857143         1         1           861003
99              152.0     0.857143         1         1           581025

    BaseAreaId  BuildingStyle EstimatedContractDate  STRAND  LivingArea  \
0       202321              2              0.016129       4         143
1       210047              1   2021-05-04 00:00:00       4         100
2       202312              2   2021-04-21 00:00:00       4         161
3       210044              1   2021-06-10 00:00:00       4         243
4       210046              1   2021-07-05 00:00:00       4          87
..         ...            ...                   ...     ...         ...
95     2100147              1   2021-07-28 00:00:00       4          36
96      210028              1   2021-06-23 00:00:00       4         142
97      202321              2   2021-06-03 00:00:00       4         139
98      210037              1   2021-07-04 00:00:00       4         139
99      210040              1   2021-06-10 00:00:00       4         118

    AuxilaryArea  MunicipalityCode  CountyCode
0              0               880           8
1            140               662           6
2             38               586           5
3             36               680           6
4              0               883           8
..           ...               ...         ...
95            10              1083          10
96            14              1080          10
97             0               884           8
98            73               861           8
99             6               581           5

[100 rows x 19 columns] (100, 19)

/var/folders/s9/fpc42dw53pgc33tc9cwdpsbh0000gp/T/ipykernel_1197/772988301.py:36: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  changed_data = changed_data.replace(a[j], b[j], regex=False)

In [21]:

def change_data_1(dataframe_original):
    dataframe = dataframe_original.copy()
    changed_data = []
    rows = np.shape(dataframe)[0]
    cols = np.shape(dataframe)[1]

    for i in range(cols):
        c = type(dataframe[f'{dataframe.axes[1][i]}'][1]) # Value of the first element in column i row 1
        if c != float and c != int:
            a = dataframe[f'{dataframe.axes[1][i]}'].unique()   # Gives the unique values of a given column
            number_of_unique_values = np.shape(a)[0]
            b = np.zeros(number_of_unique_values)
            for j in range(number_of_unique_values):
                b[j] = j / number_of_unique_values

            for row in range(rows):
                for j in range(number_of_unique_values):
                    if dataframe[f'{dataframe.axes[1][i]}'][row] == a[j]:
                        dataframe[f'{dataframe.axes[1][i]}'][row] = b[j]


    return changed_data



dataframe = df.iloc[0:100, 0:15].copy()
print(dataframe.iloc[1, 10])
# print(dataframe[5, f'{dataframe.axes[1][15]}'])
changed_data = change_data(df)
print(changed_data, np.shape(changed_data))

D
<class 'pandas.core.frame.DataFrame'>

KeyboardInterrupt:

In [34]:
# Export
# changed_data = change_data(df)
changed_data.to_parquet('changed_data.parquet')

ArrowInvalid: ("Could not convert Timestamp('2021-05-04 00:00:00') with type Timestamp: tried to convert to double", 'Conversion failed for column EstimatedContractDate with type object')

In [ ]:
df = pd.DataFrame({
    'A': [1, 2, 1],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})
df.replace({'A': 1, 'B': 5}, 99)

print(df.replace({'A': 1, 'B': 5}, 99))

In [ ]:
df = pd.read_parquet('changed_data.parquet')
df.head()